"""initial_schema

Revision ID: 3e5b8515cbf1
Revises: 
Create Date: 2026-02-27 21:36:44.515650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5b8515cbf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medecins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('specialite', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('medecins_pkey'))
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.DateTime(), nullable=False),
    sa.Column('sexe', sa.String(length=10), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('patients_pkey'))
    )
    op.create_table('implants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_implant', sa.String(length=100), nullable=False),
    sa.Column('date_pose', sa.DateTime(), nullable=False),
    sa.Column('nombre_electrodes', sa.Integer(), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_patient'], ['patients.id'], name=op.f('implants_id_patient_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('implants_pkey'))
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_incident', sa.DateTime(), nullable=False),
    sa.Column('heure_incident', sa.DateTime(), nullable=False),
    sa.Column('gravite', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('statut', sa.Enum('OUVERT', 'EN_COURS', 'RESOLU', 'FERME', name='statutincident'), nullable=True),
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.Column('id_medecin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_patient'], ['patients.id'], name=op.f('incidents_id_patient_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('incidents_pkey'))
    )
    op.create_table('rendezvous',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_rendezvous', sa.DateTime(), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.Column('id_medecin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medecin'], ['medecins.id'], name=op.f('rendezvous_id_medecin_fkey')),
    sa.ForeignKeyConstraint(['id_patient'], ['patients.id'], name=op.f('rendezvous_id_patient_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rendezvous_pkey'))
    )
    op.create_table('suivireglage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_reglage', sa.DateTime(), nullable=False),
    sa.Column('type_reglage', sa.String(length=100), nullable=False),
    sa.Column('resultat_reglage', sa.String(length=255), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.Column('id_medecin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medecin'], ['medecins.id'], name=op.f('suivireglage_id_medecin_fkey')),
    sa.ForeignKeyConstraint(['id_patient'], ['patients.id'], name=op.f('suivireglage_id_patient_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('suivireglage_pkey'))
    )
    op.create_table('processeurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_processeur', sa.String(length=100), nullable=False),
    sa.Column('date_installation', sa.DateTime(), nullable=False),
    sa.Column('batterie', sa.String(length=50), nullable=True),
    sa.Column('id_implant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_implant'], ['implants.id'], name=op.f('processeurs_id_implant_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('processeurs_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processeurs')
    op.drop_table('suivireglage')
    op.drop_table('rendezvous')
    op.drop_table('incidents')
    op.drop_table('implants')
    op.drop_table('patients')
    op.drop_table('medecins')
    # ### end Alembic commands ###
