"""ajout_table_suivi_incident

Revision ID: ee4bd16ca954
Revises: 3e5b8515cbf1
Create Date: 2026-02-27 23:19:53.320118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4bd16ca954'
down_revision: Union[str, Sequence[str], None] = '3e5b8515cbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suivi_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_suivi', sa.DateTime(), nullable=False),
    sa.Column('actions_prises', sa.String(length=2000), nullable=False),
    sa.Column('id_incident', sa.Integer(), nullable=False),
    sa.Column('id_medecin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_incident'], ['incidents.id'], name=op.f('suivi_incidents_id_incident_fkey')),
    sa.ForeignKeyConstraint(['id_medecin'], ['medecins.id'], name=op.f('suivi_incidents_id_medecin_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('suivi_incidents_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suivi_incidents')
    # ### end Alembic commands ###
